spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/springcloud?characterEncoding=utf8&useSSL=false
  jpa:
    show-sql: true
